table cotacoes
	lineageTag: 87093d2a-1ac4-4e97-9e39-8b26eacb532c

	measure 'Cotação do dia' = AVERAGE(cotacoes[Cotacao])
		displayFolder: Medidas
		lineageTag: c608d95f-ce19-4a4a-b672-cd7878d5d9cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: d724900e-1a0e-41f7-8478-0ec102da5e31
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: f082bcfd-2aeb-4f20-989a-a47abe31a62b
		summarizeBy: none
		sourceColumn: DataHora

		variation Variation
			isDefault
			relationship: a90b9be1-70a7-4f17-aa0c-440927a7e912
			defaultHierarchy: LocalDateTable_d3b4858c-60d8-4878-8fbc-be01e20be7a0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: 52f38b25-9142-46a0-a429-93ad32fa9ff0
		summarizeBy: average
		sourceColumn: Cotacao

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 121684de-54b6-4ac2-ba3a-5dd3086e81e3
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: 2bd10314-10c8-47f5-9351-f1cbe5626681
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition cotacoes = m
		mode: import
		queryGroup: Fatos
		source = getCotacoes(data_inicial, data_final)

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

